export const lightTheme = {
  mode: 'light',
  PRIMARY_BACKGROUND_COLOR: '#75E2AE',
  SECOND_BACKGROUND_COLOR: '#F88B55',
  PRIMARY_COLOR: '#75E2AE',
  SECONDARY_COLOR: '#F88B55',
  SECONDARY_TEXT_COLOR: '#F3603F',
  PRIMARY_TEXT_COLOR: '#000',
  PRIMARY_LIGHT_TEXT_COLOR: '#7C7C7C',
  TEXT_PLACEHOLDER_COLOR: '#003366',
  PRIMARY_BUTTON_COLOR: '#00BFFF',
  INPUT_BACKGROUND_COLOR: '#F7F7F7',
  WHITE_COLOR: '#FFF',
  SMALL_BODY_TEXT_COLOR:'#4C4F4D',
  PRIMARY_BORTHER_COLOR:'#cacccb50',
  LABEL_TEXT:'#B3B3B3',
  


  PRIMARY_LIGHT_COLOR: '#C02DBF',
  PRIMARY_INACTIVE_COLOR: '#32b1e940',
  BACKGROUND_COLOR: '#FFFFFF',
  INPUT_BORDER_COLOR: '#8F92A1',
  PRIMARY_BUTTON_COLOR: '#4A463C',
  SECONDARY_BUTTON_COLOR: '#FFFFFF',
  OFF_WHITE_COLOR: '#B3B3B3',
  SUCCESS_COLOR: '#56C597',
  FAILED_COLOR: 'red',
  INPUT_COLOR: '#8d87ba',
  HELPER_TEXT_COLOR: '#7862FF',
  BLACK_TEXT_COLOR: '#000',
 
  SUB_TEXT_COLOR: '#8F9BB3',


  RED:'red',
  EDIT_RED:'#F31E64',
  YELLOW:'#EFCE4A',
  GREEN:'#006400',
  BLUE:'#2080E7'
};
//#DAD5FA